repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix, "--config=pyproject.toml"]
    # Run the formatter.
    - id: ruff-format
      args: ["--config=pyproject.toml"]
# - repo: https://github.com/pycqa/isort
#   rev: 6.0.1
#   hooks:
#     - id: isort
#       name: isort (python)
