[project]
name = "pypond"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lancedb>=0.17.0",
    "pandas>=2.2.3",
    "parse>=1.20.2",
    "pydantic-to-pyarrow>=0.1.5",
]
