# automatically generated by the FlatBuffers compiler, do not modify
import flatbuffers
from catalog import serializer
from dataclasses import dataclass
from typing import List, Any


@dataclass
class Navigation:
    pass


@dataclass
class Values:
    value1: float
    value2: int
    name: str
    names: List[str]


@dataclass
class Drive:
    navigation: list[Navigation]
    images: list[float]
    uncertainty: List[float]


@dataclass
class Catalog:
    drives: list[Drive]
    values: Values
