# automatically generated by the FlatBuffers compiler, do not modify
from pydantic import BaseModel


class Navigation(BaseModel):
    dummy: bool


class Values(BaseModel):
    value1: float
    value2: int
    name: str
    names: list[str]
    navigation: Navigation


class Drive(BaseModel):
    navigation: list[Navigation]
    images: list[float]
    uncertainty: list[float]


class Catalog(BaseModel):
    drives: list[Drive]
    values: Values
