# automatically generated by the FlatBuffers compiler, do not modify
from pydantic import BaseModel
from pond import Field, File
from pond.io.readers import read_image, read_pickle
from pond.io.writers import write_image, write_pickle
from PIL import Image
from conf.catalog import Navigation, Values


class FileDrive(BaseModel):
    navigation: File[list[Navigation]] = Field(
        reader=read_pickle, writer=write_pickle, ext="pickle"
    )
    images: File[list[float]] = Field(
        reader=read_pickle, writer=write_pickle, ext="pickle"
    )
    uncertainty: list[float]


class FileCatalog(BaseModel):
    image: File[Image.Image] = Field(reader=read_image, writer=write_image, ext="png")
    drives: list[FileDrive]
    values: File[Values] = Field(reader=read_pickle, writer=write_pickle, ext="pickle")
