# Copyright 2025 Nils Bore
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# automatically generated by the FlatBuffers compiler, do not modify
from PIL import Image
from pydantic import BaseModel

from conf.catalog import Navigation, Values
from pond import Field, File
from pond.io.readers import read_image, read_pickle
from pond.io.writers import write_image, write_pickle


class FileDrive(BaseModel):
    navigation: File[list[Navigation]] = Field(
        reader=read_pickle, writer=write_pickle, ext="pickle"
    )
    images: File[list[float]] = Field(
        reader=read_pickle, writer=write_pickle, ext="pickle"
    )
    uncertainty: list[float]


class FileCatalog(BaseModel):
    image: File[Image.Image] = Field(reader=read_image, writer=write_image, ext="png")
    drives: list[FileDrive]
    values: File[Values] = Field(reader=read_pickle, writer=write_pickle, ext="pickle")
