# automatically generated by the FlatBuffers compiler, do not modify
from pydantic import BaseModel


class Car(BaseModel):
    mileage: float
    brand: str
    top_speed: float
    build_year: int


class TableCatalog(BaseModel):
    cars: list[Car]
