# Copyright 2025 Nils Bore
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# automatically generated by the FlatBuffers compiler, do not modify
import pickle
from typing import Any

from PIL import Image
from pydantic import BaseModel

from pond import Field, File


def write_pickle(object: Any, fs, path: str):
    with fs.open(path, mode="wb") as fs_file:
        pickle.dump(object, fs_file)


def read_pickle(fs, path: str) -> Any:
    with fs.open(path, mode="rb") as fs_file:
        return pickle.load(fs_file)


# NOTE: fsspec does not have type interfaces?
def write_image(im: Image.Image, fs, path: str):
    print(f"Trying to write {path}")
    with fs.open(path, mode="wb") as fs_file:
        im.save(fs_file)


def read_image(fs, path: str) -> Image.Image:
    print(f"Trying to read {path}")
    with fs.open(path, mode="rb") as fs_file:
        return Image.open(fs_file).copy()


class VariantCatalog(BaseModel):
    image: File[Image.Image] = Field(reader=read_image, writer=write_image, ext="png")
    images: list[File[Image.Image]] = Field(
        reader=read_image, writer=write_image, ext="png"
    )
    value: File[int] = Field(reader=read_pickle, writer=write_pickle, ext="pickle")
    values: list[File[int]] = Field(
        reader=read_pickle, writer=write_pickle, ext="pickle"
    )
